{% set name = "spdx-license-matcher" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/spdx/spdx-license-matcher/archive/v{{ version }}.tar.gz
  sha256: d418ec2fcb546ed29ff67fa75154d0ea3771b8883771c8a864f539b8e9069ae3

build:
  entry_points:
    - spdx-license-matcher = spdx_license_matcher.matcher:matcher
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=39.0.1
  run:
    - click ==7.0
    - jellyfish ==0.6.1
    - jpype1 >=1.3.0
    - python >={{ python_min }}
    - python-dotenv >=0.17.1
    - redis-py ==4.4.4
    - requests >=2.25

test:
  imports:
    - spdx_license_matcher
  commands:
    - pip check
    - spdx-license-matcher --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/spdx/spdx-license-matcher
  summary: A tool to match license text with SPDX license list using a an algorithm with finds close matches.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
